<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="YP1007518DT" name="Vtiger Automation" tests="2" failures="2" timestamp="11 Feb 2019 09:18:38 GMT" time="0.046" errors="0">
  <testcase name="verifyToLogOut" time="0.009" classname="testCases.LogOut_TestCase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at testActions.LogOut_POF.logout(LogOut_POF.java:13)
	at testCases.LogOut_TestCase.verifyToLogOut(LogOut_TestCase.java:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- verifyToLogOut -->
  <testcase name="verifyToLogin" time="0.028" classname="testCases.SignIn_TestCase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at testActions.SignIn_POF.signIn(SignIn_POF.java:14)
	at testCases.SignIn_TestCase.verifyToLogin(SignIn_TestCase.java:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- verifyToLogin -->
</testsuite> <!-- Vtiger Automation -->
